name: foldolino
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.0+3
  scribble: ^0.10.0+1
  flutter_riverpod: ^2.6.1
  flutter_drawing_board: ^0.9.5
  syncfusion_flutter_signaturepad: ^27.2.3
  icons_plus: ^5.0.0
  
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  share_plus: ^10.1.2
  supabase: ^2.2.7
  supabase_flutter: ^2.5.11
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Including all assets in the images and fonts folders
  assets:
    - assets/images/
    - assets/fonts/
    - assets/images/chars/

  # Specifying the custom fonts (if needed)
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Gilroy-Black.ttf
          weight: 900
        - asset: assets/fonts/Gilroy-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Gilroy-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Gilroy-Heavy.ttf
          weight: 900
        - asset: assets/fonts/Gilroy-HeavyItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Gilroy-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Gilroy-Thin.ttf
          weight: 100
        - asset: assets/fonts/Gilroy-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Gilroy-UltraLight.ttf
          weight: 200
        - asset: assets/fonts/Gilroy-UltraLightItalic.ttf
          weight: 200
          style: italic

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
      
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
 
